"""add manual payment review fields

Revision ID: 9126319bb861
Revises: a329f80d05ad
Create Date: 2026-09-08 06:16:11.904009
"""

from alembic import op
import sqlalchemy as sa


revision = '9126319bb861'
down_revision = 'a329f80d05ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_file_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('review_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_message_id')
        batch_op.drop_column('proof_file_id')

    # ### end Alembic commands ###
