"""add pending promo to users

Revision ID: a329f80d05ad
Revises: 299ec72527b4
Create Date: 2026-09-08 05:32:08.505716
"""

from alembic import op
import sqlalchemy as sa


revision = 'a329f80d05ad'
down_revision = '299ec72527b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_promo_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_promo_id')

    # ### end Alembic commands ###
