"""drop rental support

Revision ID: b27f6d02a830
Revises: 9126319bb861
Create Date: 2026-09-08 12:10:09.021783
"""

from alembic import op
import sqlalchemy as sa


revision = 'b27f6d02a830'
down_revision = '9126319bb861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('rental_hours')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_hours', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
